// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QsTuQOp5WD-ohkkWkf3EjzS-1S0I2tc',
    appId: '1:708798897300:web:4c8ed61feb76d90e4b2881',
    messagingSenderId: '708798897300',
    projectId: 'student-monitoring-app-15ef0',
    authDomain: 'student-monitoring-app-15ef0.firebaseapp.com',
    storageBucket: 'student-monitoring-app-15ef0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90ODrPeqANEmdy-hHDZIzilb0WM4BMK4',
    appId: '1:708798897300:android:277ed79f9af479dc4b2881',
    messagingSenderId: '708798897300',
    projectId: 'student-monitoring-app-15ef0',
    storageBucket: 'student-monitoring-app-15ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPprssAtW9iGgbblrw5Vip_Xkp19oLu_E',
    appId: '1:708798897300:ios:be29f7f0c86292614b2881',
    messagingSenderId: '708798897300',
    projectId: 'student-monitoring-app-15ef0',
    storageBucket: 'student-monitoring-app-15ef0.firebasestorage.app',
    iosBundleId: 'com.example.studentMonitoringApp',
  );
}
